server:
  port: 8901

spring:
  profiles:
    active: dev
#  链路追踪配置
  sleuth:
    scheduled:
      enabled: false
    baggage:
      remote-fields: X-REQUEST-IP
      correlation-fields: X-REQUEST-IP
      tag-fields: X-REQUEST-IP
  #    flyway配置
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:/db/migration
    out-of-order: true
    placeholder-replacement: false
#    应用名称
  application:
    name: soar-web
#    数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: wuxiaojian
    password: wxj123456
    url: jdbc:mysql://localhost:3306/soar-web?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 200
      max-wait: 3000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 400000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1
      filter:
        stat:
          enabled: true
        slf4j:
          enabled: true
        wall:
          enabled: true
          config:
            comment-allow: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.png,*.jpg,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: root
        login-password: 1qazCDE#5tgb
        allow:
        deny:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

#日志级别配置
logging:
  level:
    com:
      netflix:
        discovery:
          shared:
            resolver:
              aws:
                ConfigClusterResolve: WARN
      moon:
        demo:
          service:
            mapper: debug
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error
#mybstis配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mappers/*.xml


#swagger配置
swagger:
  config:
    enable: true
    groupName: demo
    basePackage: com.moon.study
    title: study-demo
    description: study-demo接口文档
    version: v2.1.0